### PR TITLE
Sahara fix provision steps

### PR DESCRIPTION
**Pull request by jeremyfreudberg**
Fix for bug introduced by #92 

Should be the final bugfix on Liberty needed. Merge this and #97 then Sahara will be open to all Kaizen users

### CODE REVIEW

**Comment by kamfonik** [comment]
@jeremyfreudberg Is the new file views_SaharaTime.py a modification of some other file I can compare it to?

**Comment by jeremyfreudberg** [comment]
It's based on `sahara_dashboard.content.data_processing.clusters.views`. I'm replacing the file. Here's the diff:
```
@@ -11,7 +11,8 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.

-from datetime import datetime
+from datetime import datetime,timedelta
+from pytz import timezone
 import json
 import logging

@@ -135,15 +136,16 @@ class ClusterEventsView(django_base.View):
                     if not event["event_info"]:
                         event["event_info"] = _("No info available")

+                utc_diff = int((86400 - datetime.now(timezone('America/New_York')).utcoffset().seconds) / 3600)
                 start_time = datetime.strptime(step["created_at"],
-                                               self._date_format)
+                                               self._date_format)-timedelta(hours=utc_diff)
                 end_time = datetime.now()
                 # Clear out microseconds. There is no need for that precision.
                 end_time = end_time.replace(microsecond=0)
                 if step["successful"] is not None:
                     updated_at = step["updated_at"]
                     end_time = datetime.strptime(updated_at,
-                                                 self._date_format)
+                                                 self._date_format)-timedelta(hours=utc_diff)
                 step["duration"] = six.text_type(end_time - start_time)

                 result = _("In progress")
```

**Comment by kamfonik** [comment]
Thanks!  +1

**Comment by radonm** [comment]
Is this working in engage1 or some staging? Engage1 will soon be update to M.

**Comment by jeremyfreudberg** [comment]
Tested in my own staging. Nothing in Engage1. Possibly fixed in Mitaka but depends on what RH includes in the Sahara package

**Comment by jeremyfreudberg** [comment]
RH package ***did not*** include the bugfix!!!

**Comment by jeremyfreudberg** [comment]
Hmm... the bugfix is not explicitly there yet we do not see the bug anyway.

**Pull request closed without merging**
