### PR TITLE
Enable heat

### PR DESCRIPTION
**Pull request by gsilvis**
Still needs to be tested, but should be pretty close.

### CODE REVIEW

**Comment by gsilvis** [comment]
Note: This requires an extra hiera parameter

quickstack::params::heat_auth_encrypt_key: [put a 16, 24, or 32 byte string here]

**Comment by gsilvis** [comment]
Bug:  The admin user cannot use heat, because you need to have the role 'heat_stack_owner' to use heat.  But there's no way in puppet to add an additional role to a user/tenant pair that has already had a role added to it.

**Comment by gsilvis** [comment]
Currently being tempest-tested

**Comment by gsilvis** [comment]
Four hiera parameters are now required

quickstack::params::heat_auth_encrypt_key: '[16, 24, or 32 byte string]'
heat::keystone::auth::region: '[region name]'
heat::keystone::auth_cfn::region: '[region name]'
heat::region_name: '[region name]'

Three tempest tests fail, but none are Heat errors. We can do a minor patch to one [change the flavor name], and disable the other two. Ready for review now

**Comment by gsilvis** [comment]
Yup, they aren't heat errors.  We can do a minor patch to one [change the flavor name], and disable the other two.  Ready for review now

**Comment by rahulait** [comment]
+1. Looks good to me.

**Comment by radonm** [comment]
+1

**Pull request merged**
