### PR TITLE
initial commit to fix nova.conf ceph issues

### PR DESCRIPTION
**Pull request by lokI8**
Fix putting ceph params into nova.conf on compute nodes, and remove the duplicate definition of /etc/nova/secret.xml in quickstack::compute_common

### CODE REVIEW

**Comment by lokI8** [comment]
I only see cinder_rbd_pool, cinder_rbd_user, and cinder_rbd_secret_uuid in both controller_common and neutron/controller. Do I need to add this parameters additionally? Are they in the structure, or should i just add them in to both files?

**Comment by ravisantoshgudimetla** [comment]
I think we already have those parameters in one of the manifests. +1 to rest of stuff

**Comment by rahulait** [comment]
@lokI8 They are missing in compute_common.pp. The default values of those variables points to something different. You can fix them the way they are set in controller_common.pp

**Comment by lokI8** [comment]
Added the 3 params that were missing. Let me know if it needs anything else =)

**Comment by rahulait** [comment]
+1 from my side as well... :+1:

**Comment by lokI8** [comment]
merging

**Pull request merged**
