### PR TITLE
Sensu puppet

### PR DESCRIPTION
**Pull request by LeonLee88**
Just add one file I mentioned. There are changes on compute_common and controller_common.

### CODE REVIEW

**Comment by gsilvis** [comment]
@LeonLee88, you don't need to close a pull request to change it.  The pull request is tied to the branch name in your fork, so just push to that branch name, and the pull request will be updated.

Same comment as before: I'd like @ravisantoshgudimetla and @rahulait to +1 this, and then you still need to fix the merge conflicts, and then I can merge it.

**Comment by rahulait** [comment]
+1 from my side.

**Comment by LeonLee88** [comment]
Just modified a check, nothing related to puppet files is changed.

**Comment by ravisantoshgudimetla** [comment]
+1 from side too with comments same as my previous one.

**Comment by gsilvis** [comment]
@LeonLee88 you still need to merge master back into this branch.  Until you do, I still can't merge this.  (P.S. it looks like your master may be very out of date---make sure you synchronize your master with CCI-MOC's master first.)

**Comment by LeonLee88** [comment]
@gsilvis @rahulait @ravisantoshgudimetla Conflicts are resolved, lastest master has been merged senu_puppet.

**Comment by gsilvis** [comment]
Okay, merging now

**Pull request merged**
