### PR TITLE
Sahara policy

### PR DESCRIPTION
**Pull request by jeremyfreudberg**
New behavior of `sahara_manage_policy: true` 

- policy.json only restricts image registry  
- no restrictions on Sahara dashboard panels except image registry  

Essentially (at the request of Orran and Ata) this will allow all users access to Sahara.

Note that someone will need to manually revert the currently existing dashboard permissions in `/usr/share/openstack-dashboard/openstack_dashboard/contrib/sahara/content/data_processing/*/panel.py` since my code isn't smart enough to undo changes...

### CODE REVIEW

**Comment by jeremyfreudberg** [comment]
I believe some concerns were voiced about some of this process needing to be done manually. Just to clarify, I am hesitant to include code in the Puppet manifests to perform what needs to be done, since it is entirely a one-time task (only affects production and a simple package update will also have the same consequences).

In the files /usr/share/openstack-dashboard/openstack_dashboard/contrib/sahara/content/data_processing/*/panel.py in production, we currently see content similar to the following:
```
from django.utils.translation import ugettext_lazy as _

import horizon

from openstack_dashboard.dashboards.project import dashboard


class ClustersPanel(horizon.Panel):
    name = _("Clusters")
    slug = 'data_processing.clusters'
    permissions = (('openstack.services.data-processing',
                    'openstack.services.data_processing'),)
    permissions = (('openstack.roles.sahara_user','openstack.roles.sahara_admin'),)


dashboard.Project.register(ClustersPanel)
```  

**All that needs to be done is removing the second** `permissions = ...` **line from each file.**  

After this is done, we don't even need to restart Apache! Simply:

` touch /usr/share/openstack-dashboard/openstack_dashboard/wsgi/django.wsgi `

**Comment by jeremyfreudberg** [comment]
So, it turns out that we recently updated the Horizon package. Actually, then, we **don't need to do any manual editing**. Just re-run Puppet after merging this PR and we should be all set.

**Comment by jeremyfreudberg** [comment]
@kamfonik

**Comment by kamfonik** [comment]
+1, I will talk to Piyanai about the timing of deploying this

**Comment by jeremyfreudberg** [comment]
Should be about time to merge/deploy this since the issue fixed by #100 was our only barrier.  

I know Orran and Ata are eagerly waiting for Sahara open to all Kaizen users (for the cloud class too) so we should try and get this done soon.  

The content of both PRs will handle everything automatically

**Comment by radonm** [comment]
Is this working in engage1 or some staging? Engage1 will soon be update to M.

**Comment by jeremyfreudberg** [comment]
Tested in my own staging. Nothing in Engage1. Possibly fixed in Mitaka but depends on what RH includes in the Sahara package

**Comment by radonm** [comment]
+1

**Comment by radonm** [comment]
+1

**Comment by jeremyfreudberg** [comment]
Mostly irrelevant

**Pull request closed without merging**
