### PR TITLE
configure swift endpoint for rados gateway

### PR DESCRIPTION
**Pull request by kamfonik**
Configured the swift endpoint to point to the radosgw.  Disable the swift_s3 endpoint which is not used.

### CODE REVIEW

**Comment by lokI8** [comment]
I thought swift was an s3 endpoint? So why is $configure_s3_endpoint false?

**Comment by lokI8** [comment]
Talked with Laura and Piyanai, we're deciding to just keep swift and hold off on enabling s3 on the gateway & in openstack until someone asks for it. I'm happy with everything else. +1 =)

**Comment by kamfonik** [comment]
To expand on Jon's note above - s3 endpoint is not currently being used by anyone, our users are all using Swift.  It is an additional set of parameters to configure and a different set of tests to check that it works.  It shouldn't be hard to turn it on if someone needs it in the future, it's just not a priority now.

**Comment by ravisantoshgudimetla** [comment]
Looks good to me. Are we planning to integrate swift with keystone. I thought we had some issues related to radosgateway if we use it with ceph. Everything else looks good to me. +1

**Comment by kamfonik** [comment]
Merging after two +1

**Pull request merged**
