### PR TITLE
iostat,vmstat,sysstat installed

### PR DESCRIPTION
**Pull request by dmak1112**
Pull request to add two new plugins to our sensu clients: Vmstat and iostat. We will then begin putting this data in influxdb for our data collection.

I installed both the plugins, and then also a package named sysstat, which is needed to run the iostat command. It runs on both of my staging nodes.

Also, I pushed them as sudo and I think for some reason this caused the author to be rado and not me. But it was me, not rado. Sorry!

Dimitri

### CODE REVIEW

**Comment by genagain** [comment]
Looks good to me! +1

**Comment by dmak1112** [comment]
Passed tempest! Needs +1 to be approved :)

**Comment by radonm** [comment]
+1

**Comment by dmak1112** [comment]
Thanks Rado!

On Thu, Jun 16, 2016 at 11:34 AM, Radoslav Milanov <notifications@github.com

**Pull request merged**
