### PR TITLE
Sahara enhancements

### PR DESCRIPTION
**Pull request by jeremyfreudberg**
This PR includes several enhancements to Sahara, including:
- Management of policy in API and dashboard
- Communication with instances over private IP through namespaces
- Plugin bugfixes
- Anti-affinity bugfix 
- Cleanup of the Puppet code itself  

Changes to hiera file:
`quickstack::params::sahara_manage_policy: true`

### CODE REVIEW

**Comment by jeremyfreudberg** [comment]
This PR also includes a bugfix resolving the issue in which Sahara instances' hosts files were populated with the incorrect entry `10.13.37.17 keystone.kaizen.massopencloud.org`.

**Comment by jeremyfreudberg** [comment]
Also see https://github.com/CCI-MOC/eng1-liberty/pull/9

**Comment by rahulait** [comment]
+1. Before merge, you need to fix permissions for sahara-rootwrap. I guess they should be 440 instead of 640 (all other files have 440 in /etc/sudoers.d directory).

**Comment by jeremyfreudberg** [comment]
Ok, done. Also threw in this bug fix: https://github.com/openstack/sahara/commit/00d8381cdc6b41951db06323bc1fabc6a42330e5

**Comment by rahulait** [comment]
+1

**Comment by jeremyfreudberg** [comment]
@radonm

**Comment by radonm** [comment]
+1

**Pull request merged**
